version: '3.5'


services:
  etcd:
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd:2379'
      ETCD_AUTO_COMPACTION_RETENTION: 1
      ETCD_DATA_DIR: '/data'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_LOGGER: 'zap'
      ETCD_NAME: stolon-etcd
    hostname: etcd
    image: 'quay.io/coreos/etcd:v3.3.9'
    volumes:
      - type: volume
        source: etcd
        target: /data

  sentinel:
    build:
      args:
        STOLON_VERSION: 0.12.0
      context: stolon/
    command:
      - '/opt/stolon/bin/stolon-sentinel'
      - '--cluster-name=pgplayground'
      - '--metrics-listen-address=0.0.0.0:8080'
      - '--store-backend=etcdv3'
      - '--store-endpoints=http://etcd:2379'
      - '--initial-cluster-spec=/cluster-seed.json'
    depends_on:
      - etcd
    hostname: sentinel
    volumes:
      - type: bind
        source: ./cluster-seed.json
        target: /cluster-seed.json

  proxy:
    build:
      args:
        STOLON_VERSION: 0.12.0
      context: stolon/
    command:
      - '/opt/stolon/bin/stolon-proxy'
      - '--cluster-name=pgplayground'
      - '--listen-address=0.0.0.0'
      - '--metrics-listen-address=0.0.0.0:8080'
      - '--store-backend=etcdv3'
      - '--store-endpoints=http://etcd:2379'
    depends_on:
      - etcd
    hostname: proxy

  node1:
    build:
      args:
        PG_PATCH: 4
        #PG_VERSION: 9.6
        #PG_VERSION_STR: 96
        PG_VERSION: 10
        PG_VERSION_STR: 10
        STOLON_VERSION: 0.12.0
      context: stolon-pg/
    command:
      - '/opt/stolon/bin/stolon-keeper'
      - '--cluster-name=pgplayground'
      - '--data-dir=/data'
      - '--metrics-listen-address=0.0.0.0:8080'
      - '--pg-listen-address=node1'
      - '--store-backend=etcdv3'
      - '--store-endpoints=http://etcd:2379'
      - '--pg-repl-auth-method=trust'
      - '--pg-repl-username=stolon'
      - '--pg-su-auth-method=trust'
    depends_on:
      - etcd
    hostname: node1
    volumes:
      - type: volume
        source: node1
        target: /data

  node2:
    build:
      args:
        PG_PATCH: 4
        #PG_VERSION: 9.6
        #PG_VERSION_STR: 96
        PG_VERSION: 10
        PG_VERSION_STR: 10
        STOLON_VERSION: 0.12.0
      context: stolon-pg/
    command:
      - '/opt/stolon/bin/stolon-keeper'
      - '--cluster-name=pgplayground'
      - '--data-dir=/data'
      - '--metrics-listen-address=0.0.0.0:8080'
      - '--pg-listen-address=node2'
      - '--store-backend=etcdv3'
      - '--store-endpoints=http://etcd:2379'
      - '--pg-repl-auth-method=trust'
      - '--pg-repl-username=stolon'
      - '--pg-su-auth-method=trust'
    depends_on:
      - etcd
    hostname: node2
    volumes:
      - type: volume
        source: node2
        target: /data

  node3:
    build:
      args:
        PG_PATCH: 4
        #PG_VERSION: 9.6
        #PG_VERSION_STR: 96
        PG_VERSION: 10
        PG_VERSION_STR: 10
        STOLON_VERSION: 0.12.0
      context: stolon-pg/
    command:
      - '/opt/stolon/bin/stolon-keeper'
      - '--cluster-name=pgplayground'
      - '--data-dir=/data'
      - '--metrics-listen-address=0.0.0.0:8080'
      - '--pg-listen-address=node3'
      - '--store-backend=etcdv3'
      - '--store-endpoints=http://etcd:2379'
      - '--pg-repl-auth-method=trust'
      - '--pg-repl-username=stolon'
      - '--pg-su-auth-method=trust'
    depends_on:
      - etcd
    hostname: node3
    volumes:
      - type: volume
        source: node3
        target: /data


volumes:
  etcd:
  node1:
  node2:
  node3:
