version: '3.5'


services:
  agent1:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb-rs'
    working_dir: '/replicante'
    links:
      - 'node1:node'
    networks:
      default:
        ipv4_address: '172.65.0.18'
    ports:
      - '37018:37017'
    volumes:
      - './agent-mongodb-rs.yaml:/replicante/agent-mongodb-rs.yaml'

  agent2:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb-rs'
    working_dir: '/replicante'
    links:
      - 'node2:node'
    networks:
      default:
        ipv4_address: '172.65.0.19'
    ports:
      - '37019:37017'
    volumes:
      - './agent-mongodb-rs.yaml:/replicante/agent-mongodb-rs.yaml'

  agent3:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb-rs'
    working_dir: '/replicante'
    links:
      - 'node3:node'
    networks:
      default:
        ipv4_address: '172.65.0.20'
    ports:
      - '37020:37017'
    volumes:
      - './agent-mongodb-rs.yaml:/replicante/agent-mongodb-rs.yaml'
