version: '3.5'


services:
  agent1:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'node1:node'
    networks:
      default:
        ipv4_address: '172.64.0.28'
    ports:
      - '37018:37017'
    volumes:
      - type: bind
        source: ./agent-mongodb.yaml
        target: /replicante/agent-mongodb.yaml

  agent2:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'node2:node'
    networks:
      default:
        ipv4_address: '172.64.0.29'
    ports:
      - '37019:37017'
    volumes:
      - type: bind
        source: ./agent-mongodb.yaml
        target: /replicante/agent-mongodb.yaml

  agent3:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'node3:node'
    networks:
      default:
        ipv4_address: '172.64.0.30'
    ports:
      - '37020:37017'
    volumes:
      - type: bind
        source: ./agent-mongodb.yaml
        target: /replicante/agent-mongodb.yaml
