version: '3.5'


services:
  node1:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
    image: mongo:3.2
    hostname: node1
    volumes:
      - type: volume
        source: node1
        target: /data/db

  node2:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
    depends_on:
      - node1
    image: mongo:3.2
    hostname: node2
    volumes:
      - type: volume
        source: node2
        target: /data/db

  node3:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
    depends_on:
      - node1
      - node2
    image: mongo:3.2
    hostname: node3
    volumes:
      - type: volume
        source: node3
        target: /data/db

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - node1
      - node2
      - node3
    image: mongo:3.2
    hostname: controller
    volumes:
      - type: bind
        source: .
        target: /files


networks:
  default:
    name: 'playgrounds_mongodb_rs'
    ipam:
      config:
        - subnet: 172.64.0.0/27


volumes:
  node1:
  node2:
  node3:
