version: '3.5'


services:
  node1:
    command:
      - 'agent'
      - '--server'
      - '--bootstrap-expect=3'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    hostname: node1
    image: consul:1.2.2
    volumes:
      - type: volume
        source: node1
        target: /consul/data

  node2:
    command:
      - 'agent'
      - '--server'
      - '--bootstrap-expect=3'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    hostname: node2
    image: consul:1.2.2
    volumes:
      - type: volume
        source: node2
        target: /consul/data

  node3:
    command:
      - 'agent'
      - '--server'
      - '--bootstrap-expect=3'
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    hostname: node3
    image: consul:1.2.2
    volumes:
      - type: volume
        source: node3
        target: /consul/data

  controller:
    command:
      - '/files/init.sh'
    hostname: controller
    image: consul:1.2.2
    volumes:
      - type: bind
        source: .
        target: /files


volumes:
  node1:
  node2:
  node3:
