FROM rust:1.26

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y cmake openjdk-8-jdk \
  && rm -rf /var/lib/apt/lists/* \
  && groupadd -r replicante \
  && useradd -r -g replicante replicante \
  && mkdir -p /replicante/agents \
  && chown -R replicante:replicante /replicante

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
    LD_LIBRARY_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server

USER replicante
WORKDIR /replicante/agents
RUN git clone --recursive https://github.com/replicante-io/agents.git . \
  && cd kafka/ \
  && cargo build
