version: '3.5'


services:
  initialiser:
    build: ../images/replicante
    command:
      - 'bash'
      - '/files/init.sh'
    links:
      - 'mongo:mongo'

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'persistence'
    image: mongo:3.6
    hostname: mongo
    volumes:
      - './data/mongo:/data/db'

  replicante:
    build: ../images/replicante
    command:
      - '/replicante/core/target/debug/replicante'
    working_dir: '/replicante'
    links:
      - 'mongo:mongo'
    networks:
      - default
      - playgrounds_mongodb_rs
    ports:
      - '16016:16016'
    volumes:
      - './replicante.yaml:/replicante/replicante.yaml'
      - './conf.d:/replicante/conf.d'

  webui:
    build: ../images/webui
    command:
      - 'npm'
      - 'run'
      - 'server'
    working_dir: '/replicante/webui'
    links:
      - 'replicante:replicante'
    ports:
      - '3000:3000'


networks:
  default:
    name: 'playgrounds_replicante'
    ipam:
      config:
        - subnet: 172.64.0.0/24

  playgrounds_mongodb_rs:
    external: true
