version: '3.5'


services:
  config1:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config1
    volumes:
      - './data/config1:/data/db'

  config2:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config2
    volumes:
      - './data/config2:/data/db'

  config3:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config3
    volumes:
      - './data/config3:/data/db'

  shard1n1:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n1
    volumes:
      - './data/shard1n1:/data/db'

  shard1n2:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n2
    volumes:
      - './data/shard1n2:/data/db'

  shard1n3:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n3
    volumes:
      - './data/shard1n3:/data/db'

  shard2n1:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n1
    volumes:
      - './data/shard2n1:/data/db'

  shard2n2:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n2
    volumes:
      - './data/shard2n2:/data/db'

  shard2n3:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n3
    volumes:
      - './data/shard2n3:/data/db'

  mongos:
    command:
      - 'mongos'
      - '--configdb'
      - 'config/config1:27019,config2:27019,config3:27019'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: mongos

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - config1
      - config2
      - config3
      - shard1n1
      - shard1n2
      - shard1n3
      - shard2n1
      - shard2n2
      - shard2n3
      - mongos
    image: mongo:3.2
    hostname: controller
    volumes:
      - './:/files'


networks:
  default:
    name: 'playgrounds_mongodb_sharded'
    ipam:
      config:
        - subnet: 172.66.0.0/24
