version: '3.5'


services:
  config1:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config1
    volumes:
      - type: volume
        source: config1
        target: /data/db

  config2:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config2
    volumes:
      - type: volume
        source: config2
        target: /data/db

  config3:
    command:
      - 'mongod'
      - '--configsvr'
      - '--replSet'
      - 'config'
    image: mongo:3.2
    hostname: config3
    volumes:
      - type: volume
        source: config3
        target: /data/db

  shard1n1:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n1
    volumes:
      - type: volume
        source: shard1n1
        target: /data/db

  shard1n2:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n2
    volumes:
      - type: volume
        source: shard1n2
        target: /data/db

  shard1n3:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard1'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard1n3
    volumes:
      - type: volume
        source: shard1n3
        target: /data/db

  shard2n1:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n1
    volumes:
      - type: volume
        source: shard2n1
        target: /data/db

  shard2n2:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n2
    volumes:
      - type: volume
        source: shard2n2
        target: /data/db

  shard2n3:
    command:
      - 'mongod'
      - '--shardsvr'
      - '--replSet'
      - 'shard2'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: shard2n3
    volumes:
      - type: volume
        source: shard2n3
        target: /data/db

  mongos:
    command:
      - 'mongos'
      - '--configdb'
      - 'config/config1:27019,config2:27019,config3:27019'
    depends_on:
      - config1
      - config2
      - config3
    image: mongo:3.2
    hostname: mongos

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - config1
      - config2
      - config3
      - shard1n1
      - shard1n2
      - shard1n3
      - shard2n1
      - shard2n2
      - shard2n3
      - mongos
    image: mongo:3.2
    hostname: controller
    volumes:
      - type: bind
        source: .
        target: /files


networks:
  default:
    name: 'playgrounds_mongodb_sharded'
    ipam:
      config:
        - subnet: 172.64.0.32/27


volumes:
  config1:
  config2:
  config3:
  shard1n1:
  shard1n2:
  shard1n3:
  shard2n1:
  shard2n2:
  shard2n3:
