version: '3.5'


services:
  agent1:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'config1:node'
    networks:
      default:
        ipv4_address: '172.64.0.53'
    volumes:
      - type: bind
        source: ./agent-mongodb-config.yaml
        target: /replicante/agent-mongodb.yaml

  agent2:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'config2:node'
    networks:
      default:
        ipv4_address: '172.64.0.54'
    volumes:
      - type: bind
        source: ./agent-mongodb-config.yaml
        target: /replicante/agent-mongodb.yaml

  agent3:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'config3:node'
    networks:
      default:
        ipv4_address: '172.64.0.55'
    volumes:
      - type: bind
        source: ./agent-mongodb-config.yaml
        target: /replicante/agent-mongodb.yaml

  agent4:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard1n1:node'
    networks:
      default:
        ipv4_address: '172.64.0.56'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent5:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard1n2:node'
    networks:
      default:
        ipv4_address: '172.64.0.57'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent6:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard1n3:node'
    networks:
      default:
        ipv4_address: '172.64.0.58'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent7:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard2n1:node'
    networks:
      default:
        ipv4_address: '172.64.0.59'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent8:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard2n2:node'
    networks:
      default:
        ipv4_address: '172.64.0.60'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent9:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'shard2n3:node'
    networks:
      default:
        ipv4_address: '172.64.0.61'
    volumes:
      - type: bind
        source: ./agent-mongodb-shard.yaml
        target: /replicante/agent-mongodb.yaml

  agent10:
    build: ../../images/agents
    command:
      - '/replicante/agents/target/debug/replicante-agent-mongodb'
    working_dir: '/replicante'
    links:
      - 'mongos:node'
    networks:
      default:
        ipv4_address: '172.64.0.62'
    volumes:
      - type: bind
        source: ./agent-mongodb-mongos.yaml
        target: /replicante/agent-mongodb.yaml
