version: '3.5'


services:
  initialiser:
    build: ../../images/replicante
    depends_on:
      - mongo
    command:
      - 'bash'
      - '/files/init.sh'

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'persistence'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  replicante:
    build: ../../images/replicante
    depends_on:
      - mongo
    command:
      - '/replicante/core/target/debug/replicante'
    working_dir: '/replicante'
    networks:
      - default
      - host
      #- playgrounds_kafka
      #- playgrounds_mongodb_rs
      #- playgrounds_mongodb_sharded
      #- playgrounds_zookeeper
    ports:
      - '16016:16016'
    volumes:
      - type: bind
        source: ./replicante.yaml
        target: /replicante/replicante.yaml
      - type: bind
        source: ./conf.d
        target: /replicante/conf.d

  webui:
    build: ../../images/webui
    depends_on:
      - replicante
    command:
      - 'npm'
      - 'run'
      - 'server'
    working_dir: '/replicante/webui'
    ports:
      - '3000:3000'


networks:
  default:
    name: 'playgrounds_replicore'
    ipam:
      config:
        - subnet: 172.32.0.0/27
  host:
    name: 'host'
    external: true

  #playgrounds_kafka: {external: true}
  #playgrounds_mongodb_rs: {external: true}
  #playgrounds_mongodb_sharded: {external: true}
  #playgrounds_zookeeper: {external: true}


volumes:
  mongo:
