version: '3.5'


services:
  initialiser:
    build: ../../images/replicante
    command:
      - 'bash'
      - '/files/init.sh'
    links:
      - 'mongo:mongo'

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'persistence'
    image: mongo:3.6
    hostname: mongo
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  replicante:
    build: ../../images/replicante
    command:
      - '/replicante/core/target/debug/replicante'
    working_dir: '/replicante'
    links:
      - 'mongo:mongo'
    networks:
      - default
      - playgrounds_kafka
      - playgrounds_mongodb_rs
      - playgrounds_mongodb_sharded
      - playgrounds_zookeeper
    ports:
      - '16016:16016'
    volumes:
      - type: bind
        source: ./replicante.yaml
        target: /replicante/replicante.yaml
      - type: bind
        source: ./conf.d
        target: /replicante/conf.d

  webui:
    build: ../../images/webui
    command:
      - 'npm'
      - 'run'
      - 'server'
    working_dir: '/replicante/webui'
    links:
      - 'replicante:replicante'
    ports:
      - '3000:3000'


networks:
  default:
    name: 'playgrounds_replicore'
    ipam:
      config:
        - subnet: 172.32.0.0/27

  playgrounds_kafka: {external: true}
  playgrounds_mongodb_rs: {external: true}
  playgrounds_mongodb_sharded: {external: true}
  playgrounds_zookeeper: {external: true}


volumes:
  mongo:
