version: '3.5'


services:
  discovery:
    build:
      context: docker-discover
    networks:
      default: {}
      replicante_playgrounds:
        ipv4_address: '172.64.255.184'
    ports:
      - '5050:5000'
    volumes:
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        read_only: true

  initialiser:
    build:
      context: init-files
    depends_on:
      - mongo

  kafka:
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 60000
      KAFKA_NUM_PARTITIONS: 64
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
    hostname: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    volumes:
      - type: volume
        source: kafka
        target: /kafka

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'persistence'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  replicante:
    depends_on:
      - kafka
      - mongo
      - zookeeper
    image: replicanteio/replicante:v0.4
    networks:
      default: {}
      replicante_playgrounds: {}
    ports:
      - '16016:16016'
    volumes:
      - type: bind
        source: ./replicante.yaml
        target: /opt/replicante/replicante.yaml
      - type: bind
        source: ./conf.d
        target: /opt/replicante/conf.d
    working_dir: '/opt/replicante'

  webui:
    depends_on:
      - replicante
    environment:
      REPLI_BACKEND_ROOT: http://replicante:16016
    image: replicanteio/webui:v0.3
    ports:
      - '3000:3000'

  zookeeper:
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    hostname: zookeeper
    image: zookeeper:3.4
    volumes:
      - type: volume
        source: zookeeper-data
        target: /data
      - type: volume
        source: zookeeper-log
        target: /datalog


networks:
  replicante_playgrounds:
    name: 'replicante_playgrounds'
    external: true


volumes:
  kafka: {}
  mongo: {}
  zookeeper-data: {}
  zookeeper-log: {}
