version: '3.5'


services:
  controller:
    command:
      - '/files/init.sh'
    environment:
      COUCHDB_USER: couch
      COUCHDB_PASSWORD: couch
    hostname: controller
    image: 'couchdb:2.1.2'
    volumes:
      - type: bind
        source: .
        target: /files

  node1:
    environment:
      COUCHDB_USER: couch
      COUCHDB_PASSWORD: couch
      NODENAME: node1.playgrounds_couchdb
    hostname: node1.playgrounds_couchdb
    image: 'couchdb:2.1.2'
    volumes:
      - type: volume
        source: node1-conf
        target: /opt/couchdb/etc/local.d
      - type: volume
        source: node1-data
        target: /opt/couchdb/data

  node2:
    environment:
      COUCHDB_USER: couch
      COUCHDB_PASSWORD: couch
      NODENAME: node2.playgrounds_couchdb
    hostname: node2.playgrounds_couchdb
    image: 'couchdb:2.1.2'
    volumes:
      - type: volume
        source: node2-conf
        target: /opt/couchdb/etc/local.d
      - type: volume
        source: node2-data
        target: /opt/couchdb/data

  node3:
    environment:
      COUCHDB_USER: couch
      COUCHDB_PASSWORD: couch
      NODENAME: node3.playgrounds_couchdb
    hostname: node3.playgrounds_couchdb
    image: 'couchdb:2.1.2'
    volumes:
      - type: volume
        source: node3-conf
        target: /opt/couchdb/etc/local.d
      - type: volume
        source: node3-data
        target: /opt/couchdb/data


networks:
  default:
    name: 'playgrounds_couchdb'


volumes:
  node1-conf:
  node1-data:
  node2-conf:
  node2-data:
  node3-conf:
  node3-data:
