version: '3.5'


services:
  node1:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: node1
    volumes:
      - type: volume
        source: node1
        target: /data/db

  node2:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
      - '--bind_ip'
      - '0.0.0.0'
    depends_on:
      - node1
    image: mongo:4.0
    hostname: node2
    volumes:
      - type: volume
        source: node2
        target: /data/db

  node3:
    command:
      - 'mongod'
      - '--replSet'
      - 'playground-mongodb-rs'
      - '--bind_ip'
      - '0.0.0.0'
    depends_on:
      - node1
      - node2
    image: mongo:4.0
    hostname: node3
    volumes:
      - type: volume
        source: node3
        target: /data/db

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - node1
      - node2
      - node3
    image: mongo:4.0
    hostname: controller
    volumes:
      - type: bind
        source: .
        target: /files


volumes:
  node1:
  node2:
  node3:
