version: '3.5'


services:
  agent1:
    build:
      context: ../images/agents
      dockerfile: Dockerfile.kafka
    command:
      - '/replicante/agents/kafka/target/debug/replicante-agent-kafka'
    working_dir: '/replicante'
    links:
      - 'node1:node'
    networks:
      default:
        ipv4_address: '172.64.0.124'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-kafka.yaml
        target: /replicante/agent-kafka.yaml

  agent2:
    build:
      context: ../images/agents
      dockerfile: Dockerfile.kafka
    command:
      - '/replicante/agents/kafka/target/debug/replicante-agent-kafka'
    working_dir: '/replicante'
    links:
      - 'node2:node'
    networks:
      default:
        ipv4_address: '172.64.0.125'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-kafka.yaml
        target: /replicante/agent-kafka.yaml

  agent3:
    build:
      context: ../images/agents
      dockerfile: Dockerfile.kafka
    command:
      - '/replicante/agents/kafka/target/debug/replicante-agent-kafka'
    working_dir: '/replicante'
    links:
      - 'node3:node'
    networks:
      default:
        ipv4_address: '172.64.0.126'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-kafka.yaml
        target: /replicante/agent-kafka.yaml
