version: '3.5'


services:
  agent1:
    command:
      - 'replicante-agent-zookeeper'
    image: replicanteio/agents:v0.4
    links:
      - 'node1:node'
    networks:
      default: {}
      replicante_playgrounds:
        ipv4_address: '172.64.255.214'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-zookeeper.yaml
        target: /opt/replicante/agent-zookeeper.yaml
    working_dir: '/opt/replicante'

  agent2:
    command:
      - 'replicante-agent-zookeeper'
    image: replicanteio/agents:v0.4
    links:
      - 'node2:node'
    networks:
      default: {}
      replicante_playgrounds:
        ipv4_address: '172.64.255.213'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-zookeeper.yaml
        target: /opt/replicante/agent-zookeeper.yaml
    working_dir: '/opt/replicante'

  agent3:
    command:
      - 'replicante-agent-zookeeper'
    image: replicanteio/agents:v0.4
    links:
      - 'node3:node'
    networks:
      default: {}
      replicante_playgrounds:
        ipv4_address: '172.64.255.212'
    volumes:
      - type: bind
        read_only: true
        source: ./agent-zookeeper.yaml
        target: /opt/replicante/agent-zookeeper.yaml
    working_dir: '/opt/replicante'


networks:
  replicante_playgrounds:
    name: 'replicante_playgrounds'
    external: true
