version: '3.5'


services:
  node1:
    environment:
      - 'cluster.name=playground-elasticsearch'
      - 'bootstrap.memory_lock=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    hostname: node1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - type: volume
        source: node1
        target: /usr/share/elasticsearch/data

  node2:
    environment:
      - 'cluster.name=playground-elasticsearch'
      - 'bootstrap.memory_lock=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.zen.ping.unicast.hosts=node1'
    hostname: node2
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - type: volume
        source: node2
        target: /usr/share/elasticsearch/data

  node3:
    environment:
      - 'cluster.name=playground-elasticsearch'
      - 'bootstrap.memory_lock=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.zen.ping.unicast.hosts=node1'
    hostname: node3
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - type: volume
        source: node3
        target: /usr/share/elasticsearch/data


volumes:
  node1:
  node2:
  node3:
