version: '3.5'


services:
  node1:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node1
    image: redis:4.0
    volumes:
      - './data/node1:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node2:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node2
    image: redis:4.0
    volumes:
      - './data/node2:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node3:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node3
    image: redis:4.0
    volumes:
      - './data/node3:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node4:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node4
    image: redis:4.0
    volumes:
      - './data/node4:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node5:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node5
    image: redis:4.0
    volumes:
      - './data/node5:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node6:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node6
    image: redis:4.0
    volumes:
      - './data/node6:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node7:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node7
    image: redis:4.0
    volumes:
      - './data/node7:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node8:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node8
    image: redis:4.0
    volumes:
      - './data/node8:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  node9:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node9
    image: redis:4.0
    volumes:
      - './data/node9:/data'
      - './redis.conf:/usr/local/etc/redis/redis.conf'

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9
    hostname: controller
    image: redis:4.0
    volumes:
      - './:/files'


networks:
  default:
    name: 'playgrounds_redis'
    ipam:
      config:
        - subnet: 172.69.0.0/24
