version: '3.5'


services:
  node1:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node1
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node1
        target: /data

  node2:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node2
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node2
        target: /data

  node3:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node3
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node3
        target: /data

  node4:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node4
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node4
        target: /data

  node5:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node5
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node5
        target: /data

  node6:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node6
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node6
        target: /data

  node7:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node7
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node7
        target: /data

  node8:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node8
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node8
        target: /data

  node9:
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    hostname: node9
    image: redis:4.0
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
      - type: volume
        source: node9
        target: /data

  controller:
    command:
      - 'bash'
      - '/files/init.sh'
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9
    hostname: controller
    image: redis:4.0
    volumes:
      - './:/files'


networks:
  default:
    name: 'playgrounds_redis'
    ipam:
      config:
        - subnet: 172.69.0.0/24


volumes:
  - node1
  - node2
  - node3
  - node4
  - node5
  - node6
  - node7
  - node8
  - node9
